// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/entities.proto

package grpc_message_go // import "github.com/aagea/grpc-message-go"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import grpc_user_go "github.com/aagea/grpc-user-go"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Source               *grpc_user_go.UserID `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination          *grpc_user_go.UserID `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message              string               `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_entities_6fa3b73cb9093c34, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSource() *grpc_user_go.UserID {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Message) GetDestination() *grpc_user_go.UserID {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *Message) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MessageList struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageList) Reset()         { *m = MessageList{} }
func (m *MessageList) String() string { return proto.CompactTextString(m) }
func (*MessageList) ProtoMessage()    {}
func (*MessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_entities_6fa3b73cb9093c34, []int{1}
}
func (m *MessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageList.Unmarshal(m, b)
}
func (m *MessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageList.Marshal(b, m, deterministic)
}
func (dst *MessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageList.Merge(dst, src)
}
func (m *MessageList) XXX_Size() int {
	return xxx_messageInfo_MessageList.Size(m)
}
func (m *MessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageList.DiscardUnknown(m)
}

var xxx_messageInfo_MessageList proto.InternalMessageInfo

func (m *MessageList) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*MessageList)(nil), "message.MessageList")
}

func init() { proto.RegisterFile("message/entities.proto", fileDescriptor_entities_6fa3b73cb9093c34) }

var fileDescriptor_entities_6fa3b73cb9093c34 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd0, 0x31, 0x4b, 0xc5, 0x30,
	0x10, 0x07, 0x70, 0xea, 0x93, 0xf7, 0x7c, 0xa9, 0x83, 0x44, 0x90, 0xd0, 0xc5, 0x52, 0x1c, 0x3a,
	0xf8, 0x2e, 0xf0, 0x5c, 0x04, 0x37, 0x71, 0x11, 0x74, 0x29, 0xba, 0xb8, 0xa5, 0xf5, 0x8c, 0x01,
	0xdb, 0x94, 0xdc, 0xf5, 0x93, 0xf9, 0x05, 0xc5, 0x36, 0xad, 0x22, 0x6e, 0xb9, 0xbb, 0x1f, 0x97,
	0x3f, 0x27, 0xce, 0x5a, 0x24, 0x32, 0x16, 0x35, 0x76, 0xec, 0xd8, 0x21, 0x41, 0x1f, 0x3c, 0x7b,
	0xb9, 0x89, 0xfd, 0xec, 0x74, 0x20, 0x0c, 0x7f, 0xa6, 0xd9, 0xb9, 0xf5, 0xde, 0x7e, 0xa0, 0x1e,
	0xab, 0x7a, 0x78, 0xd3, 0xec, 0x5a, 0x24, 0x36, 0x6d, 0x3f, 0x81, 0xe2, 0x33, 0x11, 0x9b, 0xc7,
	0x69, 0x83, 0xbc, 0x10, 0x6b, 0xf2, 0x43, 0x68, 0x50, 0x25, 0x79, 0x52, 0xa6, 0xfb, 0x63, 0xf8,
	0x5e, 0x09, 0xcf, 0x84, 0xe1, 0xfe, 0xae, 0x8a, 0x33, 0x09, 0x22, 0x7d, 0x45, 0x62, 0xd7, 0x19,
	0x76, 0xbe, 0x53, 0x07, 0xff, 0xd0, 0xdf, 0x40, 0x5e, 0x8b, 0xed, 0xf2, 0xa9, 0x5a, 0x8d, 0x3a,
	0x83, 0x29, 0x16, 0xcc, 0xb1, 0xe0, 0x69, 0x16, 0xd5, 0x0f, 0x96, 0x6a, 0x89, 0xa6, 0x0e, 0xf3,
	0xa4, 0xdc, 0x56, 0x73, 0x59, 0xdc, 0x88, 0x34, 0x3e, 0x1f, 0x1c, 0xb1, 0xbc, 0x14, 0x47, 0xf1,
	0x0a, 0xa4, 0x92, 0x7c, 0x55, 0xa6, 0xfb, 0x13, 0x88, 0x0d, 0x88, 0xae, 0x5a, 0xc4, 0x6d, 0xf1,
	0x92, 0x5b, 0xc7, 0xef, 0x43, 0x0d, 0x8d, 0x6f, 0xb5, 0x31, 0x16, 0x8d, 0xb6, 0xa1, 0x6f, 0x76,
	0x51, 0xec, 0xac, 0xaf, 0xd7, 0x63, 0xb2, 0xab, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x17,
	0x3a, 0x2a, 0x76, 0x01, 0x00, 0x00,
}
